# Generated by Django 6.0.2 on 2026-04-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    def create_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()

        if User.objects.exists():
            return
        
        superuser = User.Objects.create_superuser(
            username="gavan_raya",
            email="gavan@raya.com",
            password="G@varionSab3r",
            last_login=timezone.now()
        )

        superuser.save()

    operations = [
        migrations.RunPython(create_superuser),
        migrations.AlterField(
            model_name='article',
            name='word_count',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
